$background = 040304
$onBackground = f0e1ec
$surface = 040304
$surfaceDim = 040304
$surfaceBright = 100b10
$surfaceContainerLowest = 000000
$surfaceContainerLow = 060406
$surfaceContainer = 090609
$surfaceContainerHigh = 0c070c
$surfaceContainerHighest = 0e090e
$onSurface = f0e1ec
$surfaceVariant = 0e090e
$onSurfaceVariant = b4a7b1
$outline = 7d727b
$outlineVariant = 4f454d
$inverseSurface = fff7fa
$inverseOnSurface = 5a5358
$shadow = 000000
$scrim = 000000
$surfaceTint = 312431
$primary = e2bae0
$primaryDim = d4add2
$onPrimary = 533654
$primaryContainer = 674868
$onPrimaryContainer = ffd7fc
$inversePrimary = 755475
$primaryFixed = f9d0f7
$primaryFixedDim = ebc2e8
$onPrimaryFixed = 4f3250
$onPrimaryFixedVariant = 6d4d6d
$secondary = d8bfd4
$secondaryDim = cab2c6
$onSecondary = 4c3b4c
$secondaryContainer = 473647
$onSecondaryContainer = d0b8cd
$secondaryFixed = f5dbf1
$secondaryFixedDim = e6cde3
$onSecondaryFixed = 4b3a4b
$onSecondaryFixedVariant = 695568
$tertiary = ffc6cd
$tertiaryDim = f9b4be
$onTertiary = 6c3a43
$tertiaryContainer = f9b4be
$onTertiaryContainer = 62323a
$tertiaryFixed = f9b4be
$tertiaryFixedDim = eaa7b0
$onTertiaryFixed = 4a1e27
$onTertiaryFixedVariant = 6c3a43
$error = f97386
$errorDim = c44b5f
$onError = 490013
$errorContainer = 871c34
$onErrorContainer = ff97a3
$primaryPaletteKeyColor = 8e6c8e
$secondaryPaletteKeyColor = 867184
$tertiaryPaletteKeyColor = a16770
$neutralPaletteKeyColor = 7c757a
$neutralVariantPaletteKeyColor = 7f747d
$errorPaletteKeyColor = c74d61
$primary_paletteKeyColor = 8e6c8e
$secondary_paletteKeyColor = 867184
$tertiary_paletteKeyColor = a16770
$neutral_paletteKeyColor = 7c757a
$neutral_variant_paletteKeyColor = 7f747d
$term0 = 080808
$term1 = f148d6
$term2 = ffbac2
$term3 = ffddea
$term4 = b3a2d5
$term5 = d894d0
$term6 = 9dceff
$term7 = ead2db
$term8 = b09ea5
$term9 = ff75e1
$term10 = ffd2d5
$term11 = fff0f4
$term12 = babfdd
$term13 = e9acdd
$term14 = ffd1c0
$term15 = ffffff
$rosewater = fdedf4
$flamingo = f5daeb
$pink = fdcff8
$mauve = e9aaf4
$red = e999dd
$maroon = e5add8
$peach = fbbbdf
$yellow = ffedf2
$green = ffd8c5
$teal = dedcff
$sky = e6d3ff
$sapphire = dbb9ff
$blue = dbaaf9
$lavender = eabdfb
$klink = a075c5
$klinkSelection = a075c4
$kvisited = b063bb
$kvisitedSelection = b163ba
$knegative = d653c3
$knegativeSelection = d753c2
$kneutral = ff7cd4
$kneutralSelection = ff7cd2
$kpositive = 60adff
$kpositiveSelection = 60adff
$text = f0e1ec
$subtext1 = b4a7b1
$subtext0 = 7d727b
$overlay2 = 1a1819
$overlay1 = 171616
$overlay0 = 141213
$surface2 = 110f10
$surface1 = 0c0a0b
$surface0 = 050405
$base = 010001
$mantle = 010001
$crust = 010001
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
