$primary_paletteKeyColor = 268383
$secondary_paletteKeyColor = 627c7b
$tertiary_paletteKeyColor = 637895
$neutral_paletteKeyColor = 727878
$neutral_variant_paletteKeyColor = 6f7978
$background = 020505
$onBackground = dde4e3
$surface = 020505
$surfaceDim = 020505
$surfaceBright = 0f1110
$surfaceContainerLowest = 010303
$surfaceContainerLow = 050808
$surfaceContainer = 060a0a
$surfaceContainerHigh = 0a0d0d
$surfaceContainerHighest = 0d1010
$onSurface = dde4e3
$surfaceVariant = 111414
$onSurfaceVariant = bec9c8
$inverseSurface = dde4e3
$inverseOnSurface = 2b3231
$outline = 889392
$outlineVariant = 3f4948
$shadow = 000000
$scrim = 000000
$surfaceTint = 002d2d
$primary = 80d5d3
$onPrimary = 003737
$primaryContainer = 00504f
$onPrimaryContainer = 9cf1f0
$inversePrimary = 006a69
$secondary = b0cccb
$onSecondary = 1b3534
$secondaryContainer = 344d4d
$onSecondaryContainer = cce8e7
$tertiary = b2c8e8
$onTertiary = 1c314b
$tertiaryContainer = 7d92b0
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = 9cf1f0
$primaryFixedDim = 80d5d3
$onPrimaryFixed = 002020
$onPrimaryFixedVariant = 00504f
$secondaryFixed = cce8e7
$secondaryFixedDim = b0cccb
$onSecondaryFixed = 051f1f
$onSecondaryFixedVariant = 324b4b
$tertiaryFixed = d3e4ff
$tertiaryFixedDim = b2c8e8
$onTertiaryFixed = 041c35
$onTertiaryFixedVariant = 334863
$term0 = 080808
$term1 = 769e00
$term2 = 51e2c5
$term3 = 7cfcd4
$term4 = 75b5b5
$term5 = 7aaee9
$term6 = 82d8cd
$term7 = cddcd4
$term8 = 9aa59f
$term9 = 85b900
$term10 = 38f7d6
$term11 = ccffeb
$term12 = a3c8c5
$term13 = a2c0f7
$term14 = 89ecdd
$term15 = ffffff
$rosewater = f1f3e5
$flamingo = dfe0f5
$pink = bae2ff
$mauve = 62ceeb
$red = 8ab5ff
$maroon = abbef0
$peach = a9daac
$yellow = d2faeb
$green = 8cf1e4
$teal = 9eeeea
$sky = 93e9ec
$sapphire = 71d7de
$blue = 58ccdd
$lavender = 87d9ea
$klink = 0095a0
$klinkSelection = 0096a0
$kvisited = 008ca9
$kvisitedSelection = 008ca9
$knegative = 838f00
$knegativeSelection = 838f00
$kneutral = 34c359
$kneutralSelection = 34c359
$kpositive = 00beaf
$kpositiveSelection = 00beaf
$text = dde4e3
$subtext1 = bec9c8
$subtext0 = 889392
$overlay2 = 1c1c1c
$overlay1 = 191919
$overlay0 = 151616
$surface2 = 101212
$surface1 = 0b0e0e
$surface0 = 040707
$base = 000101
$mantle = 000101
$crust = 000101
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
