-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ############# Themes #############
hl.env("QT_QPA_PLATFORMTHEME", "qtengine")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 1)

-- ######## Toolkit backends ########
hl.env("GDK_BACKEND", "wayland,x11")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("SDL_VIDEODRIVER", "wayland,x11,windows")
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
-- ####### XDG specifications #######

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- ############# Others #############
hl.env("_JAVA_AWT_WM_NONREPARENTING", 1)
hl.env("HYPRCURSOR_THEME", "~/.local/share/icons/Bibata_modern_ice_cursor")
hl.env("HYPRCURSOR_SIZE", 24)
hl.env("XCURSOR_SIZE", 24)
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
local home = os.getenv("HOME")

-- XDG_DIRS!
hl.env("XDG_CONFIG_HOME", home .. "/.config")
hl.env("XDG_CACHE_HOME", home .. "/.cache")
hl.env("XDG_DATA_HOME", home .. "/.local/share")
hl.env("XDG_STATE_HOME", home .. "/.local/state")
hl.env("XDG_DESKTOP_DIR", home .. "/Desktop")
hl.env("XDG_DOWNLOAD_DIR", home .. "/Downloads")
hl.env("XDG_DOCUMENTS_DIR", home .. "/SYNC/Documentos")
hl.env("XDG_MUSIC_DIR", home .. "/SYNC/playlist")
hl.env("XDG_PICTURES_DIR", home .. "/Pictures")
hl.env("XDG_VIDEOS_DIR", home .. "/Vídeos")

-- Language & Tool Runtimes
hl.env("ANDROID_HOME", home .. "/.local/share/android")
hl.env("CARGO_HOME", home .. "/.local/state/cargo")
hl.env("GNUPGHOME", home .. "/.local/share/gnupg")
hl.env("RUSTUP_HOME", home .. "/.local/share/rustup")
hl.env("GOPATH", home .. "/.local/share/go")
