-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ############# Themes #############
hl.env("QT_QPA_PLATFORMTHEME", "qtengine")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 1)

-- ######## Toolkit backends ########
hl.env("GDK_BACKEND", "wayland,x11")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("SDL_VIDEODRIVER", "wayland,x11,windows")
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
-- ####### XDG specifications #######

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- ############# Others #############
hl.env("_JAVA_AWT_WM_NONREPARENTING", 1)
hl.env("HYPRCURSOR_THEME", "~/.local/share/icons/Bibata_modern_ice_cursor")
hl.env("HYPRCURSOR_SIZE", 24)
hl.env("XCURSOR_SIZE", 24)
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XDG_CONFIG_HOME", "local_var_HOME/.config")
hl.env("XDG_CACHE_HOME", "local_var_HOME/.cache")
hl.env("XDG_DATA_HOME", "local_var_HOME/.local/share")
hl.env("XDG_STATE_HOME", "local_var_HOME/.local/state")
hl.env("XDG_DESKTOP_DIR", "local_var_HOME/Desktop")
hl.env("XDG_DOWNLOAD_DIR", "local_var_HOME/Downloads")
hl.env("XDG_DOCUMENTS_DIR", "local_var_HOME/SYNC/Documentos")
hl.env("XDG_MUSIC_DIR", "local_var_HOME/SYNC/playlist")
hl.env("XDG_PICTURES_DIR", "local_var_HOME/Pictures")
hl.env("XDG_VIDEOS_DIR", "local_var_HOME/Vídeos")

-- Language & Tool Runtimes (Expanded paths manually for Hyprland safety)
hl.env("ANDROID_HOME", "local_var_HOME/.local/share/android")
hl.env("CARGO_HOME", "local_var_HOME/.local/state/cargo")
hl.env("GNUPGHOME", "local_var_HOME/.local/share/gnupg")
hl.env("RUSTUP_HOME", "local_var_HOME/.local/share/rustup")
hl.env("GOPATH", "local_var_HOME/.local/share/go")

-- App Specific
hl.env("XPLR_BOOKMARK_FILE", "local_var_HOME/.config/xplr/bookmarks")
