-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'
-- Autostart

hl.on("hyprland.start", function()
	-- Vars and setup
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("systemctl --user import-environment QT_QPA_PLATFORMTHEME WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	-- Noctalia
	hl.exec_cmd("noctalia --daemon")
	hl.exec_cmd("~/.config/hypr/scripts/xdg-portal-reset.sh")

	-- Utilities and Daemons
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("udiskie")
	hl.exec_cmd("playerctld daemon")
	hl.exec_cmd("mpd")
	hl.exec_cmd("mpDris2")

	-- Apps
	hl.exec_cmd("easyeffects --hide-window")
	hl.exec_cmd("secrets")
	hl.exec_cmd("obsidian")
	hl.exec_cmd("vesktop --enable-features=WaylandWindowDecorations --ozone-platform-hint=wayland")
	hl.exec_cmd("helium-browser")
	hl.exec_cmd("syncthing")
	hl.exec_cmd("syncthing-gtk --minimized")
end)

-- Exec (run every reload)
hl.on("config.reloaded", function()
	hl.exec_cmd("~/.config/hypr/scripts/hyprland_reload.sh")
end)
