-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--

-- plugin {

--     hyprexpo {

--         columns = 3

--         gap_size = 2

--         bg_col = rgb(000000)

--         workspace_method = first 1 # [center/first] [workspace] e.g. first 1 or center m+1

--

--         enable_gesture = true # laptop touchpad, 4 fingers

--         gesture_distance = 300 # how far is the "max"

--         gesture_positive = true # positive = swipe down. Negative = swipe up.

--     }

-- }

-- bind = SUPER, TAB, hyprexpo:expo, toggle # can be: toggle, off/disable or on/enable
