-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- WINDOW RULES

hl.window_rule({
	name = "center_1",
	
		match = "xwayland 0",
	
	center = 1,
})

-- Center all floating windows (not xwayland cause popups)

-- =========================================================================
-- Floating Rules
-- =========================================================================

-- Utilities & Controls
hl.window_rule({ "^(pavucontrol)$" , float = true})
hl.window_rule({ "org\\.pulseaudio\\.pavucontrol" , float = true })
hl.window_rule({ "blueman-manager" , float = true })
hl.window_rule({ "system-config-printer" , float = true })
hl.window_rule({ "nwg-look" , float = true })

-- File Managers & Rollers
hl.window_rule({ "^(.*nemo)$" , float = true })
hl.window_rule({ "org\\.gnome\\.FileRoller" , float = true })
hl.window_rule({ "file-roller" , float = true })

-- Media & Viewers
hl.window_rule({ "^(feh)$" , float = true })
hl.window_rule({ "^(mpv)$" , float = true })
hl.window_rule({ "^(.*org.kde.kdenlive.*)$" , float = true })
hl.window_rule({ "imv" , float = true })

-- Webcams, Screenshare & Misc Tools
hl.window_rule({ "^(guiscrcpy)$" , float = true })
hl.window_rule({ "^(.*quickshell)$" , float = true })
hl.window_rule({ "guifetch" , float = true })
hl.window_rule({ "yad" , float = true })
hl.window_rule({ "yad-icon-browser" , float = true })
hl.window_rule({ "zenity" , float = true })
hl.window_rule({ "wev" , float = true })
hl.window_rule({ "com\\.github\\.GradienceTeam\\.Gradience" , float = true })
hl.window_rule({ "^(todo)$" , float = true })

-- Theming & Launchers
hl.window_rule({ "^(wpgtk.*)$" , float = true })
hl.window_rule({ "^(Rofi)$" , float = true })

-- =========================================================================
-- Dialogs / File Pickers (Floating)
-- =========================================================================

hl.window_rule({ "^(Abrir arquivos)$" , float = true })
hl.window_rule({ "Select|Open (File|Folder)" , float = true })
hl.window_rule({ "File Operation Progress" , float = true })
hl.window_rule({ ".* Properties" , float = true })
hl.window_rule({ "Export Image as PNG" , float = true })
hl.window_rule({ "GIMP Crash Debug" , float = true })
hl.window_rule({ "Save As" , float = true })
hl.window_rule({ "Library" , float = true })

-- =========================================================================
-- Group Rules
-- =========================================================================

hl.window_rule({
	"^(hyprland-share-picker)$" ,
	group = "deny",
})

-- =========================================================================
-- Terminal Sizing
-- =========================================================================

hl.window_rule({
"^(kitty)$" ,
	size = { 720, 480 },
})

-- =========================================================================
-- Move to Workspace (Silent)
-- =========================================================================

-- Workspace 2: Creative apps
hl.window_rule({ "^(.*kdenlive.*)$" , workspace = "2 silent" })
hl.window_rule({ "^(.*krita.*)$" , workspace = "2 silent" })

-- Workspace 3: Notes
hl.window_rule({ "^(.*obsidian.*)$" , workspace = "3 silent" })

-- Workspace 4: Chat, Audio & Social
hl.window_rule({ "^(.*Spotify.*)$" , workspace = "4 silent" })
hl.window_rule({ "^(.*discord.*)$" , workspace = "4 silent" })
hl.window_rule({ "^(.*Vencord.*)$" , workspace = "4 silent" })
hl.window_rule({ "^(.*vesktop.*)$" , workspace = "4 silent" })
hl.window_rule({ "^(.*easyeffects)$" , workspace = "4 silent" })

-- Workspace 5: Browser / Web tools
hl.window_rule({ "^(.*helium.*)$" , workspace = "5 silent" })

-- Workspace 6: Game Launchers & Stores
hl.window_rule({  "^(itch)$" , workspace = "6 silent" })
hl.window_rule({  "^([Ss]team)$" , workspace = "6 silent" }) -- matches steam and Steam
hl.window_rule({  "^(gamescope)$" , workspace = "6 silent" })

-- Workspace 8: The Finals (Game)
hl.window_rule({  "^(THE FINALS)$" , workspace = "8 silent" })

-- Workspace 9: Recording
hl.window_rule({  "^(com.obsproject.Studio)$" , workspace = "9 silent" })

-- Special Workspace: Passwords / Secrets
hl.window_rule({  "^(org.gnome.World.Secrets)$" , workspace = "special silent" })

-- =========================================================================
-- Picture in Picture (PiP)
-- =========================================================================

hl.window_rule({
	 "Picture(-| )in(-| )[Pp]icture" ,
	move = { "100%-w-2%", "100%-w-3%" },
	keep_aspect_ratio = true,
	float = true,
	pin = true,
})

-- =========================================================================
-- Gaming / Performance Specifics
-- =========================================================================

-- Steam App specifics
hl.window_rule({  "steam" , rounding = 10, float = true })
hl.window_rule({  "steam_app_[0-9]+" , immediate = true, idle_inhibit = "always" })

-- =========================================================================
-- Custom Rendering Rules
-- =========================================================================

-- Force opaque for creative workflow apps
hl.window_rule({
	 "krita|gimp|inkscape|darktable|resolve|kdenlive|shotcut|blender|godot" ,
	opaque = true,
})

-- Keep background rendering active for OBS / Camera streams
hl.window_rule({
	 "com.obsproject.Studio|iriunwebcam|PNGTuberPlus|scrcpy" ,
	render_unfocused = true,
})

-- Prevent XWayland popup dimming
hl.window_rule({
	 "win[0-9]+" ,
	no_dim = true,
})

-- =========================================================================
-- Layer Rules
-- =========================================================================

hl.layer_rule({
	"rofi" ,
	animation = "slide",
})

hl.layer_rule({
	 "selection" ,
	animation = "none",
})

-- ######## Workspace rules ########

hl.workspace_rule({
	workspace = "w[tv1]s[false]",
	gaps_out = 20,
	gaps_in = 20,
})

hl.workspace_rule({
	workspace = "f[1]s[false]",
	gaps_out = 20,
	gaps_in = 20,
})

-- ######## Layer rules ########

hl.layer_rule({
	match = {
		 "match:namespace hyprpicker",
	},
	animation = "fade",
})

-- Colour picker out animation

hl.layer_rule({
	match = {
		 "match:namespace logout_dialog",
	},
	animation = "fade",
})

-- wlogout

hl.layer_rule({
	match = {
		 "match:namespace selection",
	},
	animation = "fade",
})

-- slurp

hl.layer_rule({
	match = {
		 "match:namespace wayfreeze",
	},
	animation = "fade",
})

-- Fuzzel

hl.layer_rule({
	match = {
		 "blur on",
	},
	animation = "popin 80%",
})

-- Shell

hl.layer_rule({
	match = {
		 "match:namespace caelestia-(launcher|osd|notifications|border-exclusion|area-picker)",
	},
	no_anim = true,
})

hl.layer_rule({
	match = {
		 "match:namespace caelestia-(drawers|background)",
	},
	animation = "fade",
})

hl.layer_rule({
	match = {
		 "match:namespace caelestia-border-exclusion",
	},
	order = 1,
})

hl.layer_rule({
	match = {
		 "match:namespace caelestia-bar",
	},
	order = 2,
})

-- windowrule= no_screen_share on,match:class ^(vesktop)$
