-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Dynamic Hyprland Style settings, modified by wpgtk


local vars = require("variables")

hl.config({
    general = {
        gaps_workspaces = workspaceGaps,
        gaps_in = windowGapsIn,
        gaps_out = windowGapsOut,
        border_size = windowBorderSize,
        col = {
            active_border = activeWindowBorderColour,
            inactive_border = inactiveWindowBorderColour,
        },
    },
})


hl.config({
    decoration = {
        rounding = vars.windowRounding,
        blur = {
            enabled           = vars.blurEnabled,
            xray              = vars.blurXray,
            special           = vars.blurSpecialWs,
            ignore_opacity    = true, -- Allows opacity blurring
            new_optimizations = true,
            popups            = vars.blurPopups,
            input_methods     = vars.blurInputMethods,
            size              = vars.blurSize,
            passes            = vars.blurPasses,
        },

        shadow = {
            enabled      = vars.shadowEnabled,
            range        = vars.shadowRange,
            render_power = vars.shadowRenderPower,
            color        = vars.shadowColour,
        },
    },
})

hl.config({
    group = {
        groupbar = {
            font_family = "JetBrainsMono NF ExtraBold",
            font_size = 13,
            gradients = true,
            font_weight_active = "ultraheavy",
            font_weight_inactive = "ultraheavy",
            gradient_round_only_edges = false,
            gradient_rounding = 6,
            height = 20,
            indicator_height = 0,
            gaps_in = 4,
            gaps_out = 4,
            --text_color = "rgb(" .. (c_colors.onPrimary or "ffffff") .. ")",
            --text_color_inactive = "rgb(" .. (c_colors.secondary or "aaaaaa") .. ")",
            --
            ---- Dot-notation keys wrapped with parsed dynamic colors:
            --["col.active"] = "rgba(" .. (c_colors.primaryff or "3584e4ff") .. ")",
            --["col.inactive"] = "rgba(" .. (c_colors.surfaceContainerff or "1e1e1eff") .. ")",
            --["col.locked_active"] = "rgba(" .. (c_colors.primaryff or "3584e4ff") .. ")",
            --["col.locked_inactive"] = "rgba(" .. (c_colors.secondaryff or "555555ff") .. ")",
        },
        col = {
            border_active = activeWindowBorderColour,
            border_inactive = inactiveWindowBorderColour,
            border_locked_active = activeWindowBorderColour,
            border_locked_inactive = inactiveWindowBorderColour,
        },
    },
})

--hl.plugin("hyprbars", function()
--    -- example config
--    bar_precedence_over_border = true,
--    bar_height = 24,
--    bar_title_enabled = true,
--    bar_color = "rgb(050508)",
--    col.text = "rgb(385273)",
--    bar_text_font = "Mononoki Nerd Font",
--    bar_part_of_window = true,
--    bar_text_size = 12,
--    bar_button_padding = 6,
--    -- example buttons (R -> L)
--    -- hyprbars-button = color, size, on-click
--    hyprbars-button = { "rgb(050508)", 18, "󰝙", "hyprctl dispatch killactive", "rgb(385273)" },
--    hyprbars-button = { "rgb(050508)", 18, "", "hyprctl dispatch fullscreen 1", "rgb(773e46)" },
--    hyprbars-button = { "rgb(050508)", 18, "󰩖", "hyprctl dispatch togglefloating", "rgb(457e84)" },
--end)

-- Toggle HyprExpo

-- bind = SUPER, grave, hyprexpo:expo, toggle # can be: toggle, off/disable or on/enable
