-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.workspace_rule({ workspace = "1", default_name = "", persistent = true })
hl.workspace_rule({ workspace = "2", default_name = "", persistent = true })
hl.workspace_rule({ workspace = "3", default_name = "", persistent = true })
hl.workspace_rule({ workspace = "4", default_name = "", persistent = true })
hl.workspace_rule({ workspace = "5", default_name = "", persistent = true })
hl.workspace_rule({ workspace = "6", default_name = "", persistent = true })
hl.workspace_rule({ workspace = "7", default_name = "" })
hl.workspace_rule({ workspace = "8", default_name = "" })
hl.workspace_rule({ workspace = "9", default_name = "" })
hl.workspace_rule({ workspace = "10", default_name = "" })
