-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    screencopy = {
        max_fps = 60,
        allow_token_by_default = true,
    },
})
-- NOTE: Section 'screencopy' may be a plugin or custom section; verify the output
