[settings]
set_wallpaper = false
gtk = false
active = 9
light_theme = false
editor = kitty -e nvim
execute_cmd = false
command = hyprctl reload
backend = colorthief
alpha = 255
smart_sort = false
auto_adjust = true
reload = false
keywords = default
vte = false
terminal = false

[keywords]

