config_version = 12

[audio]
enable_sounds = true

[bar]
order = [ "default" ]

    [bar.default]
    center = [ "clock" ]
    end = [ "tray", "group:g2", "session" ]
    margin_ends = 0
    padding = 20
    position = "left"
    radius_bottom_left = 0
    radius_top_left = 0
    scale = 1.300000011920929
    start = [ "launcher", "workspaces" ]
    thickness = 48

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "notifications", "bar", "volume", "bluetooth", "network", "brightness", "battery" ]
        opacity = 1.0
        padding = 6.0

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "notifications", "bar_2", "volume", "network", "bluetooth", "brightness", "battery" ]
        opacity = 1.0
        padding = 8.0

[calendar]
enabled = true

    [calendar.account.personal_google]
    type = "google"

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000002", "desktop-widget-0000000000000005" ]

    [desktop_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 176.0
    box_width = 352.0
    cx = 1632.0
    cy = 988.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false
        background_opacity = 0.0
        center_text = true
        clock_style = "digital"
        format = "{:%H : %M│}"
        shadow = true

    [desktop_widgets.widget.desktop-widget-0000000000000005]
    box_height = 102.66666412353516
    box_width = 102.66666412353516
    cx = 1830.0
    cy = 988.0
    output = "HDMI-A-1"
    rotation = -0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000005.settings]
        background = false
        center_text = false
        format = "{:%d\\n%b}"

[dock]
auto_hide = true
background_opacity = 0.99999997764825821
enabled = true
icon_size = 32
reserve_space = false
show_dots = true

[hooks]
colors_changed = "killall -s USR1 kitty & killall -s USR1 nvim"
wallpaper_changed = ""

[hot_corners.bottom_left]
action = "launcher"

[hot_corners.top_left]
action = "window_switcher"

[hot_corners.top_right]
action = "control_center"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[keybinds]
down = [ "Down", "Ctrl+j" ]
left = [ "Left", "Ctrl+h" ]
right = [ "Right", "Ctrl+l" ]
up = [ "Up", "Ctrl+k" ]

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 957.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        center_password_text = false
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 128.0
    box_width = 256.0
    cx = 960.0
    cy = 700.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        shadow = false

[osd]
background_opacity = 0.99999997764825821

[plugins]
enabled = [ "noctalia/timer", "noctalia/kaomoji" ]

[shell]
avatar_path = "~/.face.icon"
font_family = "Rubik"
launch_apps_as_systemd_services = true
panel_anchor_bar = "default"
password_style = "random"
polkit_agent = true

    [shell.animation]
    speed = 1.3000000193715096

    [shell.greeter_sync]
    auto_sync = true
    privilege_command = "sudo"

    [shell.launcher]
    app_grid = true

    [shell.panel]
    control_center_placement = "floating"
    open_near_click_control_center = true
    open_near_click_session = true
    open_near_click_wallpaper = true
    wallpaper_placement = "floating"

    [shell.screen_corners]
    enabled = true

    [shell.screenshot]
    confirm_region = true
    show_cursor = true

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    command = "sudo systemctl suspend"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    command = "sudo systemctl reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

[theme]
builtin = "Ayu"
community_palette = "Rose Pine Moon Alt"
mode = "dark"
pure_black_dark = true
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4", "hyprland", "kcolorscheme", "kitty", "qt", "starship" ]
    community_ids = [ "discord", "neovim", "obsidian", "prismlauncher", "obs", "hyprtoolkit", "papirus-icons", "lazygit" ]

[wallpaper]
directory = "/home/vvn/Wallpapers"
transition_on_startup = true

    [wallpaper.automation]
    enabled = true

    [wallpaper.default]
    path = "/home/vvn/Wallpapers/t2.jpg"

    [wallpaper.last]
    path = "/home/vvn/Wallpapers/t2.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/vvn/Wallpapers/t2.jpg"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/vvn/Wallpapers/xenia.png"
    theme_mode = "dark"
    wallpaper_scheme = "m3-tonal-spot"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/vvn/Wallpapers/apo0.gif"
    theme_mode = "dark"
    wallpaper_scheme = "m3-tonal-spot"

[weather]
effects = false

[widget.audio_visualizer]
width = 256

[widget.bar]
type = "noctalia/timer:bar"

[widget.bar_2]
type = "noctalia/timer:bar"

[widget.battery]
display_mode = "glyph"
show_label = false

[widget.bluetooth]
hide_when_no_connected_device = true

[widget.brightness]
show_label = false

[widget.clock]
capsule_radius = "auto"
format = "{:%H:··:%M}"

[widget.launcher]
capsule = true
capsule_fill = "primary"
capsule_foreground = "on_primary"
font_weight = 1000
glyph = "gender-transgender"
scale = 1.0

[widget.network]
show_label = false

[widget.session]
capsule = true
color = "tertiary"

[widget.tray]
drawer = true
drawer_item_size = 22.0
match_adjacent_spacing = true
scale = 1.1500000000000001

[widget.volume]
show_label = false

[widget.workspaces]
capsule = true
empty_color = "on_secondary"
label_source = "name"
max_label_chars = 2
occupied_color = "on_secondary"
pill_scale = 0.70000000000000007
scale = 0.90000000000000013
scroll_repeat = "steps"
show_labels = true
style = "minimal"